<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use App\Models\Property;
use App\Models\User;

class PropertySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get existing property owners
        $owners = User::where('role', 'property_owner')->get();
        
        if ($owners->isEmpty()) {
            $this->command->warn('No property owners found. Creating sample properties without owners.');
        }

        $properties = [
            [
                'name' => 'Toscana Malioboro',
                'description' => 'Homestay Minimalis moderen dengan sentuhan ala hotel mini dengan dua kamar tidur dan satu kamar mandi lengkap dengan shower dan waterheater. terletak di lokasi yang strategis 15menit dari Malioboro dan 10 menit ke alun alun kidul. nyaman untuk rombongan keluarga dengan satu tempat parkir mobil dengan taman outdoor.',
                'address' => 'Jl. Nitiprayan, Jomegatan, Ngestiharjo, Kec. Kasihan, Kabupaten Bantul, Daerah Istimewa Yogyakarta 55184, Indonesia',
                'maps_link' => 'https://maps.app.goo.gl/BzZaMQ7NWjbDSndh6',
                'latitude' => -7.815969535,
                'longitude' => 110.3432223,
                'capacity' => 6,
                'capacity_max' => 6,
                'bedroom_count' => 2,
                'bathroom_count' => 1,
                'base_rate' => 600000,
                'weekend_premium_percent' => 25,
                'extra_bed_rate' => 75000,
                'house_rules' => '',
                'check_in_time' => '14:00:00',
                'check_out_time' => '11:00:00',
                'min_stay_weekday' => 1,
                'min_stay_weekend' => 2,
                'min_stay_peak' => 2,
                'is_featured' => true,
            ],
            [
                'name' => 'Pavilo A',
                'description' => 'Unit ini berlokasi strategis di pusat kota Yogyakarta, menawarkan tempat yang nyaman dan minimalis, ideal untuk keluarga atau berkumpul bersama teman-teman selama liburan. Hanya 10 menit dari destinasi wisata populer seperti Malioboro, unit ini memberikan kemudahan akses untuk menikmati pesona kota. Fasilitas di unit ini dirancang untuk kenyamanan Anda. Tersedia kasur spring bed 2 in 1 yang dapat menampung hingga 4 orang, dilengkapi dengan AC untuk memastikan tidur yang nyenyak. Kamar mandi modern dengan air panas memberikan pengalaman mandi yang menyegarkan setelah seharian beraktivitas. Selain itu, unit ini juga menyediakan fasilitas laundry seperti mesin cuci, setrika, dan meja setrika, sangat cocok bagi Anda yang menginap lebih lama. Dengan suasana yang nyaman dan lokasi yang strategis, unit ini adalah pilihan sempurna untuk menikmati liburan di Yogyakarta bersama keluarga atau sahabat. Rasakan kenyamanan seperti di rumah sendiri sambil menjelajahi keindahan kota!',
                'address' => 'Jl.Pakuncen No.7, Wirobrajan, Yogyakarta',
                'maps_link' => 'https://maps.app.goo.gl/s6PbbFfCMQeK76PRA',
                'latitude' => -7.795256129,
                'longitude' => 110.3521633,
                'capacity' => 4,
                'capacity_max' => 4,
                'bedroom_count' => 1,
                'bathroom_count' => 1,
                'base_rate' => 350000,
                'weekend_premium_percent' => 29,
                'extra_bed_rate' => 75000,
                'house_rules' => '',
                'check_in_time' => '14:00:00',
                'check_out_time' => '11:00:00',
                'min_stay_weekday' => 1,
                'min_stay_weekend' => 2,
                'min_stay_peak' => 2,
                'is_featured' => false,
            ],
            [
                'name' => 'Pavilo B',
                'description' => 'Unit ini berlokasi strategis di pusat kota Yogyakarta, menawarkan tempat yang nyaman dan minimalis, ideal untuk keluarga atau berkumpul bersama teman-teman selama liburan. Hanya 10 menit dari destinasi wisata populer seperti Malioboro, unit ini memberikan kemudahan akses untuk menikmati pesona kota. Fasilitas di unit ini dirancang untuk kenyamanan Anda. Tersedia kasur spring bed 2 in 1 yang dapat menampung hingga 4 orang, dilengkapi dengan AC untuk memastikan tidur yang nyenyak. Kamar mandi modern dengan air panas memberikan pengalaman mandi yang menyegarkan setelah seharian beraktivitas. Selain itu, unit ini juga menyediakan fasilitas laundry seperti mesin cuci, setrika, dan meja setrika, sangat cocok bagi Anda yang menginap lebih lama. Dengan suasana yang nyaman dan lokasi yang strategis, unit ini adalah pilihan sempurna untuk menikmati liburan di Yogyakarta bersama keluarga atau sahabat. Rasakan kenyamanan seperti di rumah sendiri sambil menjelajahi keindahan kota!',
                'address' => 'Jl.Pakuncen No.7, Wirobrajan, Yogyakarta',
                'maps_link' => 'https://maps.app.goo.gl/s6PbbFfCMQeK76PRA',
                'latitude' => -7.795414305,
                'longitude' => 110.3520639,
                'capacity' => 4,
                'capacity_max' => 6,
                'bedroom_count' => 1,
                'bathroom_count' => 1,
                'base_rate' => 400000,
                'weekend_premium_percent' => 25,
                'extra_bed_rate' => 75000,
                'house_rules' => '',
                'check_in_time' => '14:00:00',
                'check_out_time' => '11:00:00',
                'min_stay_weekday' => 1,
                'min_stay_weekend' => 2,
                'min_stay_peak' => 2,
                'is_featured' => false,
            ],
            [
                'name' => 'Terakota',
                'description' => 'Unit ini terletak di jantung kota, hanya berjarak sekitar 10 menit dari destinasi wisata ikonik Malioboro, membuatnya sangat strategis untuk berlibur atau perjalanan bisnis Anda. Hunian ini dirancang untuk memberikan kenyamanan maksimal dengan berbagai fasilitas modern yang lengkap. Tersedia dua kamar tidur yang dilengkapi dengan AC, memastikan tidur Anda tetap nyaman meski cuaca panas. Kamar mandi di unit ini sudah dilengkapi dengan air panas, memberikan pengalaman mandi yang menyenangkan setelah seharian beraktivitas. Untuk kebutuhan memasak, tersedia perlengkapan dapur yang lengkap, mulai dari alat memasak hingga peralatan makan, sehingga Anda bisa menikmati makanan layaknya di rumah sendiri. Selain itu, unit ini juga menyediakan fasilitas tambahan seperti mesin cuci, setrika, dan meja setrika yang sangat berguna untuk Anda yang menginap dalam waktu lama. Semua kebutuhan Anda, baik untuk liburan santai maupun perjalanan kerja, bisa terpenuhi di sini. Dengan lokasi strategis dan fasilitas lengkap, hunian ini menjadi pilihan sempurna untuk pengalaman menginap yang menyenangkan!',
                'address' => 'Jl. Waru, Kdipiro, Ngestiharjo, Kec. Kasihan, Kabupaten Bantul, Daerah Istimewa Yogyakarta 55184',
                'maps_link' => 'https://maps.app.goo.gl/GsW8L4Webit6S1Rn7',
                'latitude' => -7.798632368,
                'longitude' => 110.344282,
                'capacity' => 5,
                'capacity_max' => 6,
                'bedroom_count' => 2,
                'bathroom_count' => 1,
                'base_rate' => 500000,
                'weekend_premium_percent' => 30,
                'extra_bed_rate' => 75000,
                'house_rules' => '',
                'check_in_time' => '14:00:00',
                'check_out_time' => '11:00:00',
                'min_stay_weekday' => 1,
                'min_stay_weekend' => 2,
                'min_stay_peak' => 2,
                'is_featured' => false,
            ],
            [
                'name' => 'Lopelop',
                'description' => 'Unit ini menawarkan suasana tenang dan asri, ideal untuk Anda yang mencari kenyamanan selama menginap. Didesain dengan fasilitas lengkap, unit ini cocok untuk keluarga kecil atau perjalanan bersama teman. Terdapat 2 kamar tidur yang dilengkapi dengan AC, memberikan kenyamanan optimal untuk istirahat Anda. Selain itu, unit ini memiliki 2 kamar mandi modern dengan fasilitas air panas, menjadikan pengalaman mandi Anda lebih menyenangkan, terutama di pagi atau malam hari. Untuk Anda yang gemar memasak, dapur di unit ini sudah dilengkapi dengan perlengkapan memasak dan makan yang lengkap, memudahkan Anda menyiapkan hidangan favorit. Fasilitas laundry juga tersedia, seperti mesin cuci, setrika, dan meja setrika, memastikan kenyamanan bagi tamu yang menginap lebih lama. Dengan suasana yang menenangkan, fasilitas lengkap, dan desain yang fungsional, unit ini adalah pilihan tepat untuk pengalaman menginap yang nyaman dan praktis. Cocok untuk liburan santai, perjalanan bisnis, atau sekadar melepas penat.',
                'address' => 'Jl. Menayu Kulon, Menayu Lor, Tirtonirmolo, Kec. Kasihan, Kabupaten Bantul, Daerah Istimewa Yogyakarta 55184',
                'maps_link' => 'https://maps.app.goo.gl/Fm3qzMDz8GdHiYHB8',
                'latitude' => -7.824525793,
                'longitude' => 110.3375349,
                'capacity' => 5,
                'capacity_max' => 6,
                'bedroom_count' => 2,
                'bathroom_count' => 2,
                'base_rate' => 550000,
                'weekend_premium_percent' => 27,
                'extra_bed_rate' => 75000,
                'house_rules' => '',
                'check_in_time' => '14:00:00',
                'check_out_time' => '11:00:00',
                'min_stay_weekday' => 1,
                'min_stay_weekend' => 2,
                'min_stay_peak' => 2,
                'is_featured' => false,
            ],
            [
                'name' => 'Abrenara',
                'description' => 'Berada di lokasi strategis di pusat kota, unit ini menjadi pilihan sempurna untuk Anda yang ingin menikmati suasana Malioboro dan sekitarnya. Hanya selangkah dari berbagai destinasi wisata, unit ini menawarkan kenyamanan layaknya rumah sendiri dengan fasilitas lengkap yang memanjakan Anda dan keluarga. Unit ini dilengkapi dengan 4 kamar tidur ber-AC yang dirancang untuk kenyamanan maksimal. Nikmati tidur berkualitas setelah seharian menjelajahi kota. Terdapat pula 3 kamar mandi modern yang sudah dilengkapi dengan fasilitas air panas, memastikan kenyamanan Anda setiap saat. Untuk Anda yang gemar memasak, dapur unit ini menyediakan peralatan memasak dan makan yang lengkap, sehingga Anda bisa menikmati hidangan favorit bersama keluarga. Selain itu, fasilitas seperti mesin cuci, setrika, dan meja setrika juga tersedia, memastikan kebutuhan Anda selama menginap tetap terpenuhi. Lokasi yang strategis, fasilitas lengkap, dan kenyamanan maksimal menjadikan unit ini pilihan ideal untuk liburan atau perjalanan bisnis Anda. Segera pesan dan rasakan pengalaman menginap yang tak terlupakan!',
                'address' => 'Jl. Tjokro Riverview No.B2, Pakuncen, Wirobrajan, Kota Yogyakarta, Yogyakarta',
                'maps_link' => 'https://maps.app.goo.gl/L4EhZAWBpGKuN1Ht5',
                'latitude' => -7.7956881,
                'longitude' => 110.3543126,
                'capacity' => 6,
                'capacity_max' => 9,
                'bedroom_count' => 3,
                'bathroom_count' => 3,
                'base_rate' => 700000,
                'weekend_premium_percent' => 29,
                'extra_bed_rate' => 75000,
                'house_rules' => '',
                'check_in_time' => '14:00:00',
                'check_out_time' => '11:00:00',
                'min_stay_weekday' => 1,
                'min_stay_weekend' => 2,
                'min_stay_peak' => 2,
                'is_featured' => true,
            ],
            [
                'name' => 'Sunshine',
                'description' => 'Unit ini terletak di Perumahan Tjokro Riverview, sebuah lokasi yang nyaman dan strategis untuk Anda yang ingin tinggal dekat dengan pusat kota Yogyakarta. Hanya berjarak sekitar 10 menit dari kawasan wisata Malioboro, unit ini memungkinkan Anda menikmati keindahan kota, wisata belanja, dan kuliner khas Yogyakarta dengan mudah tanpa harus menempuh perjalanan jauh. Dirancang untuk memenuhi kebutuhan Anda dan keluarga, unit ini menawarkan fasilitas lengkap yang memberikan kenyamanan maksimal. Terdapat 3 kamar tidur yang masing-masing sudah dilengkapi dengan pendingin udara (AC), memastikan kesejukan dan kenyamanan sepanjang hari. Selain itu, tersedia 2 kamar mandi modern yang dilengkapi dengan air panas, sehingga Anda dapat menikmati mandi dengan relaksasi penuh kapan saja. Untuk kebutuhan dapur, unit ini telah dilengkapi dengan peralatan memasak dan makan yang memadai, memungkinkan Anda untuk menyajikan hidangan favorit keluarga dengan praktis. Tidak hanya itu, tersedia pula fasilitas rumah tangga tambahan, seperti mesin cuci, setrika, dan meja setrika, yang dirancang untuk mempermudah aktivitas harian Anda.',
                'address' => 'Jl. Tjokro Riverview No.A8, Pakuncen, Wirobrajan, Kota Yogyakarta, Yogyakarta',
                'maps_link' => 'https://maps.app.goo.gl/Z3mKUerLT7wpwCv78',
                'latitude' => -7.795662279,
                'longitude' => 110.3544173,
                'capacity' => 6,
                'capacity_max' => 9,
                'bedroom_count' => 3,
                'bathroom_count' => 2,
                'base_rate' => 700000,
                'weekend_premium_percent' => 29,
                'extra_bed_rate' => 75000,
                'house_rules' => '',
                'check_in_time' => '14:00:00',
                'check_out_time' => '11:00:00',
                'min_stay_weekday' => 1,
                'min_stay_weekend' => 2,
                'min_stay_peak' => 2,
                'is_featured' => false,
            ],
            [
                'name' => 'Araya',
                'description' => 'Guesthouse Arayya adalah akomodasi nyaman dua lantai yang terletak di pusat Kota Yogyakarta. Dengan fasilitas lengkap dan lokasi strategis, penginapan ini sempurna untuk liburan keluarga atau perjalanan bisnis Anda, memberikan akses mudah ke berbagai destinasi populer di Jogja.',
                'address' => 'Jl. Tjokro Riverview No.C5 , Pakuncen, Wirobrajan, Kota Yogyakarta, Yogyakarta',
                'maps_link' => 'https://maps.app.goo.gl/Rg1YC2JRqeW8w9ty5',
                'latitude' => -7.795600493,
                'longitude' => 110.3546044,
                'capacity' => 6,
                'capacity_max' => 9,
                'bedroom_count' => 3,
                'bathroom_count' => 2,
                'base_rate' => 650000,
                'weekend_premium_percent' => 31,
                'extra_bed_rate' => 75000,
                'house_rules' => '',
                'check_in_time' => '14:00:00',
                'check_out_time' => '11:00:00',
                'min_stay_weekday' => 1,
                'min_stay_weekend' => 2,
                'min_stay_peak' => 2,
                'is_featured' => false,
            ],
            [
                'name' => 'Cendana',
                'description' => 'Nikmati kenyamanan menginap di Candani Homestay, berlokasi strategis dekat Tugu Yogyakarta. Dengan desain modern minimalis dan fasilitas lengkap, homestay ini cocok untuk liburan keluarga atau perjalanan bisnis Anda di Jogja',
                'address' => 'Bener, Kec. Tegalrejo, Kota Yogyakarta, Daerah Istimewa Yogyakarta',
                'maps_link' => 'https://maps.app.goo.gl/13yoWBheRXJvzuHH9?g_st=iwb',
                'latitude' => -7.778885666,
                'longitude' => 110.35398,
                'capacity' => 6,
                'capacity_max' => 9,
                'bedroom_count' => 3,
                'bathroom_count' => 2,
                'base_rate' => 700000,
                'weekend_premium_percent' => 29,
                'extra_bed_rate' => 75000,
                'house_rules' => '',
                'check_in_time' => '14:00:00',
                'check_out_time' => '11:00:00',
                'min_stay_weekday' => 1,
                'min_stay_weekend' => 2,
                'min_stay_peak' => 2,
                'is_featured' => false,
            ],
            [
                'name' => 'Cakrawala',
                'description' => 'Unit ini berlokasi di Perumahan Bumi Cakrawala, menawarkan suasana tenang yang cocok untuk tempat tinggal nyaman. Dengan lokasi strategis, Jogja City Mall dapat dicapai hanya dalam 5 menit, memberikan kemudahan akses ke pusat perbelanjaan dan hiburan. Unit ini dilengkapi dengan 3 kamar tidur ber-AC, 1 kamar mandi dengan fasilitas air panas, dan 1 toilet. Untuk kebutuhan harian, tersedia peralatan memasak dan makan, mesin cuci, setrika, serta meja setrika. Fasilitas lengkap ini dirancang untuk mendukung kenyamanan dan kemudahan penghuni. Dengan suasana yang asri, lokasi strategis, dan fasilitas yang memadai, unit ini adalah pilihan ideal bagi Anda yang menginginkan hunian praktis dan nyaman.',
                'address' => 'Jl. Bhumi Cakrawala 17, Kutu Patran, Sinduadi, Kec. Mlati, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55284',
                'maps_link' => 'https://maps.app.goo.gl/rt9ZJQck87Y3Z2zs5',
                'latitude' => -7.749682034,
                'longitude' => 110.360327,
                'capacity' => 6,
                'capacity_max' => 9,
                'bedroom_count' => 3,
                'bathroom_count' => 2,
                'base_rate' => 700000,
                'weekend_premium_percent' => 29,
                'extra_bed_rate' => 75000,
                'house_rules' => '',
                'check_in_time' => '14:00:00',
                'check_out_time' => '11:00:00',
                'min_stay_weekday' => 1,
                'min_stay_weekend' => 2,
                'min_stay_peak' => 2,
                'is_featured' => false,
            ],
            [
                'name' => 'Sun Emerald',
                'description' => 'Terletak di perumahan elite Citra Grand Mutiara, unit ini menawarkan suasana tenang dan asri, sempurna untuk tempat istirahat yang nyaman. Dengan desain modern dan fasilitas lengkap, unit ini dirancang untuk memenuhi kebutuhan Anda selama menginap. Unit ini memiliki 4 kamar tidur yang dilengkapi dengan AC untuk kenyamanan maksimal. Tersedia 2 kamar mandi modern dengan fasilitas air panas, serta tambahan 1 toilet untuk kemudahan Anda. Dapur unit ini menyediakan peralatan masak dan makan yang lengkap, memungkinkan Anda menyiapkan hidangan favorit tanpa kendala. Untuk mendukung kenyamanan harian, unit ini juga dilengkapi dengan fasilitas mesin cuci, setrika, dan meja setrika. Semua kebutuhan Anda akan terpenuhi dengan mudah, sehingga Anda bisa menikmati waktu berkualitas bersama keluarga atau rekan. Lokasi strategis, suasana asri, dan fasilitas unggulan menjadikan unit ini pilihan ideal untuk liburan atau perjalanan bisnis Anda. Jangan lewatkan pengalaman menginap yang nyaman dan menyenangkan di Homsjogja .',
                'address' => 'Emerald Hill Road, Jatipereng, Balecatur, Kec. Gamping, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55295',
                'maps_link' => 'https://maps.app.goo.gl/kizLF5qSv3HjA556A',
                'latitude' => -7.814567392,
                'longitude' => 110.284246,
                'capacity' => 8,
                'capacity_max' => 14,
                'bedroom_count' => 4,
                'bathroom_count' => 2,
                'base_rate' => 800000,
                'weekend_premium_percent' => 38,
                'extra_bed_rate' => 75000,
                'house_rules' => '',
                'check_in_time' => '14:00:00',
                'check_out_time' => '11:00:00',
                'min_stay_weekday' => 1,
                'min_stay_weekend' => 2,
                'min_stay_peak' => 2,
                'is_featured' => true,
            ],
            [
                'name' => 'Sunjava Sunrise',
                'description' => 'Berada di lokasi strategis di pusat kota, unit ini menjadi pilihan sempurna untuk Anda yang ingin menikmati suasana Malioboro dan sekitarnya. Hanya selangkah dari berbagai destinasi wisata, unit ini menawarkan kenyamanan layaknya rumah sendiri dengan fasilitas lengkap yang memanjakan Anda dan keluarga. Unit ini dilengkapi dengan 4 kamar tidur ber-AC yang dirancang untuk kenyamanan maksimal. Nikmati tidur berkualitas setelah seharian menjelajahi kota. Terdapat pula 3 kamar mandi modern yang sudah dilengkapi dengan fasilitas air panas, memastikan kenyamanan Anda setiap saat. Untuk Anda yang gemar memasak, dapur unit ini menyediakan peralatan memasak dan makan yang lengkap, sehingga Anda bisa menikmati hidangan favorit bersama keluarga. Selain itu, fasilitas seperti mesin cuci, setrika, dan meja setrika juga tersedia, memastikan kebutuhan Anda selama menginap tetap terpenuhi. Lokasi yang strategis, fasilitas lengkap, dan kenyamanan maksimal menjadikan unit ini pilihan ideal untuk liburan atau perjalanan bisnis Anda. Segera pesan dan rasakan pengalaman menginap yang tak terlupakan!',
                'address' => 'Jl.Pakuncen No.7, Wirobrajan, Yogyakarta',
                'maps_link' => 'https://maps.app.goo.gl/sEqMxMRYyRGUvNYM6',
                'latitude' => -7.795368795,
                'longitude' => 110.3520814,
                'capacity' => 8,
                'capacity_max' => 12,
                'bedroom_count' => 4,
                'bathroom_count' => 3,
                'base_rate' => 850000,
                'weekend_premium_percent' => 29,
                'extra_bed_rate' => 75000,
                'house_rules' => '',
                'check_in_time' => '14:00:00',
                'check_out_time' => '11:00:00',
                'min_stay_weekday' => 1,
                'min_stay_weekend' => 2,
                'min_stay_peak' => 2,
                'is_featured' => false,
            ],
            [
                'name' => 'Sunjava Sunset',
                'description' => 'Unit ini berada di pusat kota Yogyakarta, menawarkan lokasi strategis dengan akses mudah ke berbagai destinasi wisata populer. Hanya membutuhkan waktu sekitar 10 menit untuk mencapai Malioboro, Nol Kilometer, dan Alun-Alun Utara, menjadikan unit ini pilihan ideal bagi wisatawan yang ingin menjelajahi keindahan kota. Dirancang untuk kenyamanan maksimal, unit ini dilengkapi dengan 4 kamar tidur yang semuanya ber-AC, menciptakan suasana sejuk dan nyaman sepanjang hari. Terdapat 3 kamar mandi modern dengan fasilitas air panas, memberikan kenyamanan ekstra bagi Anda dan keluarga. Selain itu, unit ini juga menyediakan fasilitas laundry seperti mesin cuci, setrika, dan meja setrika, sangat praktis untuk tamu yang menginap lebih lama. Dengan perpaduan lokasi strategis, fasilitas lengkap, dan suasana nyaman, unit ini adalah tempat sempurna untuk menikmati liburan Anda di Yogyakarta. Cocok untuk keluarga besar atau perjalanan bersama teman!',
                'address' => 'Jl.Pakuncen No.7, Wirobrajan, Yogyakarta',
                'maps_link' => 'https://maps.app.goo.gl/sEqMxMRYyRGUvNYM6',
                'latitude' => -7.795368795,
                'longitude' => 110.3520814,
                'capacity' => 8,
                'capacity_max' => 12,
                'bedroom_count' => 4,
                'bathroom_count' => 3,
                'base_rate' => 850000,
                'weekend_premium_percent' => 29,
                'extra_bed_rate' => 75000,
                'house_rules' => '',
                'check_in_time' => '14:00:00',
                'check_out_time' => '11:00:00',
                'min_stay_weekday' => 1,
                'min_stay_weekend' => 2,
                'min_stay_peak' => 2,
                'is_featured' => false,
            ],
            [
                'name' => 'Sunjava Sunday',
                'description' => 'Berada di lokasi strategis di pusat kota, unit ini menjadi pilihan sempurna untuk Anda yang ingin menikmati suasana Malioboro dan sekitarnya. Hanya selangkah dari berbagai destinasi wisata, unit ini menawarkan kenyamanan layaknya rumah sendiri dengan fasilitas lengkap yang memanjakan Anda dan keluarga. Unit ini dilengkapi dengan 4 kamar tidur ber-AC yang dirancang untuk kenyamanan maksimal. Nikmati tidur berkualitas setelah seharian menjelajahi kota. Terdapat pula 3 kamar mandi modern yang sudah dilengkapi dengan fasilitas air panas, memastikan kenyamanan Anda setiap saat. Untuk Anda yang gemar memasak, dapur unit ini menyediakan peralatan memasak dan makan yang lengkap, sehingga Anda bisa menikmati hidangan favorit bersama keluarga. Selain itu, fasilitas seperti mesin cuci, setrika, dan meja setrika juga tersedia, memastikan kebutuhan Anda selama menginap tetap terpenuhi. Lokasi yang strategis, fasilitas lengkap, dan kenyamanan maksimal menjadikan unit ini pilihan ideal untuk liburan atau perjalanan bisnis Anda. Segera pesan dan rasakan pengalaman menginap yang tak terlupakan!',
                'address' => 'Jl.Pakuncen No.7, Wirobrajan, Yogyakarta',
                'maps_link' => 'https://maps.app.goo.gl/sEqMxMRYyRGUvNYM6',
                'latitude' => -7.795368795,
                'longitude' => 110.3520814,
                'capacity' => 8,
                'capacity_max' => 12,
                'bedroom_count' => 4,
                'bathroom_count' => 3,
                'base_rate' => 850000,
                'weekend_premium_percent' => 29,
                'extra_bed_rate' => 75000,
                'house_rules' => '',
                'check_in_time' => '14:00:00',
                'check_out_time' => '11:00:00',
                'min_stay_weekday' => 1,
                'min_stay_weekend' => 2,
                'min_stay_peak' => 2,
                'is_featured' => false,
            ],
            [
                'name' => 'Villa Cubic',
                'description' => 'Cubic Villa ini adalah villa dengan lokasi yang sangat strategis dengan 4 kamar ac dan 3 kamar mandi disertai air panas, dan kelebihan cubic villa ini yaitu memiliki Privat Pool dengan bangunan baru konsep milenial membuat kalian menginap disin nyaman dan betah',
                'address' => 'Jl. Palagan Regency No.A6, Jatirejo, Sendangadi, Kec. Mlati, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55285',
                'maps_link' => 'https://maps.app.goo.gl/XCq7dHsWgRQwbBAx8',
                'latitude' => -7.735811062,
                'longitude' => 110.3726987,
                'capacity' => 8,
                'capacity_max' => 12,
                'bedroom_count' => 4,
                'bathroom_count' => 3,
                'base_rate' => 1300000,
                'weekend_premium_percent' => 31,
                'extra_bed_rate' => 100000,
                'house_rules' => '',
                'check_in_time' => '14:00:00',
                'check_out_time' => '11:00:00',
                'min_stay_weekday' => 1,
                'min_stay_weekend' => 2,
                'min_stay_peak' => 2,
                'is_featured' => true,
            ],
            [
                'name' => 'Villahoms',
                'description' => 'Mempunyai teras, Villahoms - 3 Bedroom Villa in Yogyakarta menyediakan akomodasi di Ngaglik dengan WiFi gratis dan pemandangan taman. Vila ini mempunyai kolam renang pribadi, taman, dan parkir pribadi gratis.Vila ber-AC 3 kamar tidur ini dilengkapi dengan tempat duduk, TV layar datar, dan dapur dengan kulkas. Handuk dan seprai disediakan di vila.Vila menawarkan hot tub.Monumen Tugu berjarak 10 km dari Ubu Villahoms - 3 Bedroom Villa in Yogyakarta, sementara Mal Malioboro terletak sejauh 10 km. Bandara terdekat adalah Bandara Adisutjipto, 16 km dari Ubu Villa Flamboyan - 3 Bedroom Villa in Yogyakarta.',
                'address' => 'Jl. Flamboyan, Rejodani 1, Sariharjo, Kec. Ngaglik, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55581',
                'maps_link' => 'https://maps.app.goo.gl/tmLDkqw7U3hMRBG3A',
                'latitude' => -7.716189582,
                'longitude' => 110.3765327,
                'capacity' => 8,
                'capacity_max' => 15,
                'bedroom_count' => 3,
                'bathroom_count' => 2,
                'base_rate' => 1300000,
                'weekend_premium_percent' => 31,
                'extra_bed_rate' => 100000,
                'house_rules' => '',
                'check_in_time' => '14:00:00',
                'check_out_time' => '11:00:00',
                'min_stay_weekday' => 1,
                'min_stay_weekend' => 2,
                'min_stay_peak' => 2,
                'is_featured' => true,
            ],
            [
                'name' => 'Villa Abaia',
                'description' => 'Unit ini terletak di perumahan Taman Palagan Asri 2, menawarkan suasana yang tenang dan asri, cocok untuk Anda yang mencari kenyamanan dan ketenangan selama menginap. Dengan lingkungan yang hijau dan udara segar, hunian ini menjadi tempat ideal untuk liburan bersama keluarga atau teman. Fasilitas di unit ini sangat lengkap untuk memenuhi kebutuhan Anda. Tersedia 4 kamar tidur yang semuanya dilengkapi dengan AC, memastikan kenyamanan maksimal. Selain itu, terdapat 2 kamar mandi modern dengan air panas, serta 1 toilet tambahan untuk kemudahan seluruh penghuni. Untuk kebutuhan memasak, dapur sudah dilengkapi dengan peralatan memasak dan makan yang lengkap, sehingga Anda bisa menyiapkan hidangan favorit dengan mudah. Bagi Anda yang menginap dalam waktu lama, unit ini juga menyediakan fasilitas laundry, termasuk mesin cuci, setrika, dan meja setrika. Fasilitas unggulan lainnya adalah kolam renang khusus anak-anak, yang akan menjadi hiburan menyenangkan bagi si kecil selama menginap. Dengan suasana yang nyaman dan fasilitas yang lengkap, unit ini adalah pilihan sempurna untuk pengalaman menginap yang menyenangkan dan berkesan.',
                'address' => 'Karang Moko, Sariharjo, Kec. Ngaglik, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55581',
                'maps_link' => 'https://maps.app.goo.gl/HgvUVwvqfH8A9EHJ8',
                'latitude' => -7.732277562,
                'longitude' => 110.376175,
                'capacity' => 8,
                'capacity_max' => 12,
                'bedroom_count' => 4,
                'bathroom_count' => 2,
                'base_rate' => 950000,
                'weekend_premium_percent' => 32,
                'extra_bed_rate' => 75000,
                'house_rules' => '',
                'check_in_time' => '14:00:00',
                'check_out_time' => '11:00:00',
                'min_stay_weekday' => 1,
                'min_stay_weekend' => 2,
                'min_stay_peak' => 2,
                'is_featured' => false,
            ],
        ];

        foreach ($properties as $index => $propertyData) {
            // Create unique slug with timestamp to avoid duplicates
            $baseSlug = Str::slug($propertyData['name']);
            $slug = $baseSlug;
            
            // Check if slug exists and append timestamp if needed
            $counter = 1;
            while (Property::where('slug', $slug)->exists()) {
                $slug = $baseSlug . '-' . time() . '-' . $counter;
                $counter++;
            }

            // Assign owner if available
            $owner = $owners->get($index % $owners->count());
            
            Property::create([
                'name' => $propertyData['name'],
                'slug' => $slug,
                'description' => $propertyData['description'],
                'address' => $propertyData['address'],
                'maps_link' => $propertyData['maps_link'],
                'lat' => $propertyData['latitude'],
                'lng' => $propertyData['longitude'],
                'capacity' => $propertyData['capacity'],
                'capacity_max' => $propertyData['capacity_max'],
                'bedroom_count' => $propertyData['bedroom_count'],
                'bathroom_count' => $propertyData['bathroom_count'],
                'base_rate' => $propertyData['base_rate'],
                'weekend_premium_percent' => $propertyData['weekend_premium_percent'],
                'extra_bed_rate' => $propertyData['extra_bed_rate'],
                'house_rules' => $propertyData['house_rules'],
                'check_in_time' => $propertyData['check_in_time'],
                'check_out_time' => $propertyData['check_out_time'],
                'min_stay_weekday' => $propertyData['min_stay_weekday'],
                'min_stay_weekend' => $propertyData['min_stay_weekend'],
                'min_stay_peak' => $propertyData['min_stay_peak'],
                'is_featured' => $propertyData['is_featured'],
                'seo_title' => $propertyData['name'],
                'seo_description' => $propertyData['description'],
                'seo_keywords' => $propertyData['name'],
                'owner_id' => $owner?->id,
                'created_at' => now(),
                'updated_at' => now(),
            ]);

            $this->command->info("Created property: {$propertyData['name']} with slug: {$slug}");
        }

        $this->command->info('Property seeder completed successfully!');
    }
}
