<?php

namespace App\Services;

use App\Models\Article;
use App\Models\ContentPlan;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

class ArticleService
{
    /**
     * Create a new article and handle associated logic
     */
    public function createArticle(array $data): Article
    {
        return DB::transaction(function () use ($data) {
            $article = Article::create([
                ...$data,
                'author_id' => Auth::id(),
                'published_at' => ($data['status'] ?? '') === 'published' ? now() : null,
            ]);

            if (!empty($data['property_ids'])) {
                $article->properties()->attach($data['property_ids']);
            }

            // Note: ContentPlan auto-creation is now handled by ArticleObserver

            return $article;
        });
    }

    /**
     * Update an article and sync associated data
     */
    public function updateArticle(Article $article, array $data): Article
    {
        return DB::transaction(function () use ($article, $data) {
            $updateData = [
                ...$data,
                'published_at' => ($data['status'] ?? '') === 'published' && !$article->published_at
                    ? now()
                    : $article->published_at,
            ];

            $article->update($updateData);

            if (isset($data['property_ids'])) {
                $article->properties()->sync($data['property_ids']);
            }

            if (isset($data['outline']) && $article->content_plan_id) {
                $article->contentPlan->update(['ai_outline' => $data['outline']]);
            }

            return $article;
        });
    }

    /**
     * Duplicate an existing article
     */
    public function duplicateArticle(Article $article): Article
    {
        return DB::transaction(function () use ($article) {
            $newArticle = $article->replicate();
            $newArticle->title = $article->title . ' (Copy)';
            $newArticle->slug = null; // Auto-generated by model or observer
            $newArticle->status = 'draft';
            $newArticle->published_at = null;
            $newArticle->scheduled_at = null;
            $newArticle->view_count = 0;
            $newArticle->click_count = 0;
            $newArticle->author_id = Auth::id();
            $newArticle->save();

            $newArticle->properties()->attach($article->properties->pluck('id'));

            return $newArticle;
        });
    }

    /**
     * Publish an article
     */
    public function publishArticle(Article $article): bool
    {
        return DB::transaction(function () use ($article) {
            $article->update([
                'status' => 'published',
                'published_at' => now(),
                'scheduled_at' => null,
            ]);

            // Sync handled by ArticleObserver

            return true;
        });
    }

    /**
     * Schedule an article
     */
    public function scheduleArticle(Article $article, \DateTime $dateTime): bool
    {
        return $article->update([
            'status' => 'scheduled',
            'scheduled_at' => $dateTime,
        ]);
    }

    /**
     * Update article performance metrics
     */
    public function updateMetrics(Article $article, ?int $viewCount = null, ?int $clickCount = null, ?float $timeOnPage = null): void
    {
        $data = [];

        if ($viewCount !== null) {
            $data['view_count'] = $article->view_count + $viewCount;
        }

        if ($clickCount !== null) {
            $data['click_count'] = $article->click_count + $clickCount;
        }

        if ($timeOnPage !== null) {
            if ($article->avg_time_on_page) {
                $data['avg_time_on_page'] = ($article->avg_time_on_page + $timeOnPage) / 2;
            } else {
                $data['avg_time_on_page'] = $timeOnPage;
            }
        }

        if (!empty($data)) {
            $article->update($data);
        }
    }
}
