<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('ai_escalations', function (Blueprint $table) {
            $table->id();
            $table->string('escalation_id', 100)->unique(); // Generated by AI service
            $table->string('conversation_id', 100)->nullable();
            $table->foreignId('lead_id')->nullable()->constrained('ai_leads')->nullOnDelete();
            $table->enum('trigger', [
                'closing_intent',
                'discount_request',
                'complaint',
                'refund_request',
                'custom_request',
                'out_of_knowledge',
                'explicit_request',
                'negative_sentiment',
                'vip_detected',
            ]);
            $table->enum('urgency', ['critical', 'high', 'medium', 'low'])->default('medium');
            $table->text('summary');
            $table->json('context')->nullable(); // preferred_unit, dates, quote_id, total_price
            $table->string('recommended_action', 500)->nullable();
            $table->enum('channel_preference', ['whatsapp', 'phone', 'email'])->default('whatsapp');
            $table->enum('status', ['created', 'claimed', 'in_progress', 'resolved', 'abandoned'])->default('created');
            $table->foreignId('claimed_by')->nullable()->constrained('users')->nullOnDelete();
            $table->timestamp('claimed_at')->nullable();
            $table->timestamp('resolved_at')->nullable();
            $table->boolean('notification_dashboard')->default(false);
            $table->boolean('notification_whatsapp')->default(false);
            $table->timestamps();

            $table->index(['status', 'urgency']);
            $table->index('conversation_id');
            $table->index('created_at');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('ai_escalations');
    }
};
