<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('ai_conversations', function (Blueprint $table) {
            $table->id();
            $table->string('conversation_id', 100)->unique(); // Generated by AI service
            $table->enum('channel', ['web_chat', 'whatsapp', 'instagram'])->default('web_chat');
            $table->string('user_identifier', 200)->nullable(); // anonymous session or user_id
            $table->foreignId('lead_id')->nullable()->constrained('ai_leads')->nullOnDelete();
            $table->enum('status', ['active', 'escalated', 'closed', 'abandoned'])->default('active');
            $table->string('summary', 500)->nullable();
            $table->json('tags')->nullable();
            $table->timestamp('started_at')->nullable();
            $table->timestamp('last_activity_at')->nullable();
            $table->timestamps();

            $table->index(['status', 'channel']);
            $table->index('last_activity_at');
        });

        Schema::create('ai_conversation_messages', function (Blueprint $table) {
            $table->id();
            $table->foreignId('conversation_id')->constrained('ai_conversations')->cascadeOnDelete();
            $table->enum('role', ['user', 'assistant', 'system', 'tool']);
            $table->text('content');
            $table->json('metadata')->nullable(); // tools_called, latency_ms, tokens, cost
            $table->timestamp('sent_at');
            $table->timestamps();

            $table->index(['conversation_id', 'sent_at']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('ai_conversation_messages');
        Schema::dropIfExists('ai_conversations');
    }
};
